name: Auto Pull Latest Code

on: workflow_dispatch
 
jobs:
  pull_latest_code:
    runs-on: self-hosted 

    steps:
    - name: Navigate to previous git folder and pull changes
      run: |
        cd "C:\src\gs-spring-boot"
        #git clone https://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@github.com/ashokdevopsorg/gs-spring-boot.git
        git pull 
        git fetch --prune
        git checkout develop
