name: Deploy Repository A

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        if: github.ref == 'refs/heads/master'  # Only run this step if the branch is master
        uses: actions/checkout@v4
        with:
          ref: master  # Checkout code from the master branc
      
      - name: Remove Existing Files from Destination Folder
        shell: pwsh
        run: |
          Remove-Item -Path "D:\TfsData*" -Recurse -Force

      - name: Move Code to Destination Folder
        shell: pwsh
          run: |
        
        # Move all folders and files to the destination folder
            Move-Item -Path * -Destination "D:\TfsData" -Force
